version: '3'

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: contacts-api:latest
    env_file: ./.env
    ports:
      - "5000:$PORT"

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "$DB_PASS"
      MYSQL_DATABASE: "$DB_NAME"
    ports:
      - 3306:3306

  # adminer:
  #   image: adminer:4.7
  #   restart: always
  #   ports:
  #     - 8080:8080
